Revert "Remove unused arguments from analyse_file"
This reverts commit 78cc57a136ec21292e376c9b029a3959ffd9faa7, which
created the following regression:

File list contains 96627 files
-------------------------
Analysis...
Extracted metadata from 0 files
Analyse phase took 0:00:10.663482
-------------------------
Crossreferencing...
Making prefix tree
Traceback (most recent call last):
  File "./run.py", line 192, in <module>
    do_the_business()
  File "./run.py", line 158, in do_the_business
    crossreference.crossreference(file_list=file_list,dbfile_name=dbfile_name,logfile=logfile,use_multiprocessing=use_multiprocessing)
  File
    "/var/www/judgmental.org.uk/judgmental/judgmental/crossreference.py",
  line 29, in crossreference
    citationtree.populate(sorted_citations)
  File
  "/var/www/judgmental.org.uk/judgmental/judgmental/prefixtree.py",
  line 303, in populate
    raise ValueError("Can't populate with the emptyset")
  ValueError: Can't populate with the emptyset